Changed list to set
susemeee/yrumee pull request #5
Opened 2021-04-23 15:30 UTC by havana723

- 밥집 관리를 리스트에서 셋으로 수정하였습니다.
- 저장된 밥집이 50개를 넘을 경우 출력한 밥집을 삭제하도록 수정하였습니다.

2021-04-23 15:42 UTC, SkeletonK10 requested changes

2021-04-23 15:42 UTC, SkeletonK10 commented on yrumee/modules/what_to_eat.py
> +            if len(target_food_list) < 50:
`if len(target_food_list) > 50:`

2021-04-24 16:57 UTC, havana723 commented on yrumee/modules/what_to_eat.py
> +            if len(target_food_list) < 50:
수정하였습니다

2021-04-25 03:51 UTC, merged

2021-04-25 03:51 UTC, susemeee commented
마이그레이션 후 적용